### ISSUE TITLE
Question regarding services.ldap.id

### ISSUE THREAD

**Issue by Senshi00** [wekan/ldap#75]
Hello wekan Team,

I wanted to ask how the services.ldap.id is being generated? Which information is it using from LDAP to generate this value? Thank you for your assistance.

Regards

**Comment by xet7** [comment]
@Senshi00 

Wekan LDAP code is here:
https://github.com/wekan/wekan/tree/master/packages/wekan-ldap

If some LDAP user knows more, please add a comment to this issue.
