### ISSUE TITLE
not showing ldap authentication

### ISSUE THREAD

**Issue by veloprofz** [wekan/ldap#96]
srv configuration:
Wekan + snap

WeKan ® Version | 6.09.0
Meteor version | 2.2
Node version | 12.22.10
MongoDB version | 3.2.22
OS Type | Linux/x64/5.10.0-21-amd64

![image](https://user-images.githubusercontent.com/125956266/220278644-4fc64126-3ac9-4dcd-9c1e-c25d404a5aff.png)

**Comment by xet7** [comment]
@veloprofz 

https://github.com/wekan/wekan/wiki/LDAP

# Snap

sudo snap set wekan ldap-enable='true'

# Docker

https://github.com/wekan/wekan/blob/master/docker-compose.yml#L488

**Comment by xet7** [comment]
@veloprofz 

Please stopping adding duplicate questions in other unrelated issues. Thanks!

**Comment by veloprofz** [comment]
after this command not show this option in admin panel.

**Comment by veloprofz** [comment]
> @veloprofz
> 
> Please stopping adding duplicate questions in other unrelated issues. Thanks!

**Comment by veloprofz** [comment]
> @veloprofz
> 
> https://github.com/wekan/wekan/wiki/LDAP
> # Snap
> 
> sudo snap set wekan ldap-enable='true'
> # Docker
> 
> https://github.com/wekan/wekan/blob/master/docker-compose.yml#L488

after this command not show this option in admin panel.

**Comment by xet7** [comment]
@veloprofz 

Did you add other LDAP options like listed here?

https://github.com/wekan/wekan/wiki/LDAP

**Comment by veloprofz** [comment]
> @veloprofz
> 
> Did you add other LDAP options like listed here?
> 
> https://github.com/wekan/wekan/wiki/LDAP

of course, I looked at everything related to snap:

https://raw.githubusercontent.com/wekan/wekan/devel/snap-src/bin/config => 404: Not Found

after this command:

sudo snap set wekan ldap-enable='true'
sudo snap set wekan default-authentication-method='ldap'
sudo snap set wekan ldap-fullname-field='CN'

does not show ldap option.
![image](https://user-images.githubusercontent.com/125956266/220477837-2b75a1a1-6673-404c-92c4-c6d1692f36d9.png)

**Comment by xet7** [comment]
@veloprofz

Where did you get this old URL ? Is there error at some wiki page?

https://raw.githubusercontent.com/wekan/wekan/devel/snap-src/bin/config

This is correct URL:

https://raw.githubusercontent.com/wekan/wekan/master/snap-src/bin/config

**Comment by xet7** [comment]
@veloprofz 

Your screenshot does not show this:
```
ldap-enable true
```
Did you run this command?
```
sudo snap set wekan ldap-enable='true'
```

**Comment by veloprofz** [comment]
> @veloprofz
> 
> Where did you get this old URL ? Is there error at some wiki page?
> 
> https://raw.githubusercontent.com/wekan/wekan/devel/snap-src/bin/config
> 
> This is correct URL:
> 
> https://raw.githubusercontent.com/wekan/wekan/master/snap-src/bin/config

Example from setting listed at [this config file](https://raw.githubusercontent.com/wekan/wekan/devel/snap-src/bin/config):
https://github.com/wekan/wekan-snap/wiki/Supported-settings-keys

**Comment by xet7** [comment]
@veloprofz 

Thanks! I fixed those links.

**Comment by xet7** [comment]
@veloprofz 

You could make backup and try upgrading to WeKan Snap Candidate: https://github.com/wekan/wekan/issues/4780

**Comment by veloprofz** [comment]
> 



> sudo snap set wekan ldap-enable='true'

Thx, after this 

> @veloprofz
> 
> Your screenshot does not show this:
> 
> ```
> ldap-enable true
> ```
> 
> Did you run this command?
> 
> ```
> sudo snap set wekan ldap-enable='true'
> ```

Thx, after this command show this option.

**Comment by veloprofz** [comment]
> @veloprofz
> 
> You could make backup and try upgrading to WeKan Snap Candidate: [wekan/wekan#4780](https://github.com/wekan/wekan/issues/4780)

thx , I installed another server based on Centos and now there is the new version:

![image](https://user-images.githubusercontent.com/125956266/220481685-c943c515-47df-443c-82cf-b44c2122204e.png)
